### ISSUE TITLE
Safari 7+ has a different icon

### ISSUE THREAD

**Issue by mzgol** [WordPress/browsehappy#26] opened 2015-09-02 18:08 UTC
Safari 7+ has a different icon than the one displayed on the site. The current one is available at https://raw.githubusercontent.com/alrra/browser-logos/master/safari/safari.png:
![Safari 9 icon](https://raw.githubusercontent.com/alrra/browser-logos/master/safari/safari.png)

**Comment by Otto42** [comment] 2015-09-02 18:40
Duplicate of #25

**Closed by Otto42** 2015-09-02 18:40 UTC

**Comment by mzgol** [comment] 2015-09-02 18:44
That's what I get for searching in issues only instead of in PRs as well. Sorry!
