### ISSUE TITLE
Incorrect Edge version.

### ISSUE THREAD

**Issue by jdalton** [WordPress/browsehappy#38] opened 2016-09-28 15:34 UTC
While the UI version is up in the 30's the platform version is the one folks should key off of and it's currently v14.

**Comment by Viper007Bond** [comment] 2016-10-10 22:14
I disagree. This would be like displaying a Webkit version when talking about Chrome versions.

For those without Windows, this is what's displayed at the bottom of the settings panel:

![new_tab_ -_microsoft_edge_2016-10-10_15-13-10](https://cloud.githubusercontent.com/assets/406254/19252889/36a7e3de-8efc-11e6-83d7-17513105ac54.png)

**Comment by jdalton** [comment] 2016-10-10 22:24
Hi @Viper007Bond!

I work on MS Edge. Please see our [blog post over versioning](https://blogs.windows.com/msedgedev/2015/09/21/understanding-versions-in-an-evergreen-browser/#oWvZXfv5z4oF8flz.97):
> For sites or other resources that are primarily concerned with tracking availability of web standards and other developer-facing features, we recommend tracking against the EdgeHTML version number, rather than the Edge app version number (described further below). 
Read more at https://blogs.windows.com/msedgedev/2015/09/21/understanding-versions-in-an-evergreen-browser/#QZO2grS67R5l91Ib.99

And other resources like:
<table>
<tr><td>
<img src="https://cloud.githubusercontent.com/assets/4303/19252982/ceed947c-8efc-11e6-885c-2282ffc37bc3.png">
</td></tr>
<tr><td>
<img width="913" src="https://cloud.githubusercontent.com/assets/4303/19253016/0a08c7ca-8efd-11e6-887b-64a0b4faacc5.png">
</td></tr>
<tr><td>
<img width="958" src="https://cloud.githubusercontent.com/assets/4303/19253031/272dda0c-8efd-11e6-9e1b-67e2c2842857.png">
</td></tr>
<tr><td>
<img width="548" src="https://cloud.githubusercontent.com/assets/4303/19253069/59f7860e-8efd-11e6-9775-b7113ccb65d4.png">
</td></tr>
</table>

**Comment by Viper007Bond** [comment] 2016-10-10 23:33
Thanks for the additional context, both about who you are and more importantly about the prior art. You've convinced me. 👍

**Comment by Krinkle** [comment] 2016-11-01 22:18
This has regressed further as there is currently no Microsoft Edge version displayed on http://browsehappy.com/

<img width="1162" alt="screen shot 2016-11-01 at 22 18 01" src="https://cloud.githubusercontent.com/assets/156867/19909774/16cdad50-a081-11e6-9739-90d4bf20dc9c.png">


Most likely caused by #37, which can be fixed by #39.

**Closed** 2017-08-09 21:30 UTC
